###
GET http://localhost:3003/api/blogs HTTP/1.1

###
GET http://localhost:3003/ HTTP/1.1

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
    
{ 
  "title": "Bible",
	"author": "Some Dudes",
	"url": "https://www.google.com/",
	"likes": 10000000
}
